export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SAVE_WORKOUT = 'SAVE_WORKOUT';
export const GET_WORKOUTS = 'GET_WORKOUTS';
export const UPDATE_CURRENT_WORKOUT = 'UPDATE_CURRENT_WORKOUT';